////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./regdefs.h
//
// Project:	ZipVersa, Versa Brd implementation using ZipCPU infrastructure
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga autofpga -d -o . clock.txt global.txt dlyarbiter.txt version.txt buserr.txt pic.txt pwrcount.txt spio.txt rtclight.txt wbuconsole.txt bkram.txt zipmaster.txt mem_flash_bkram.txt mem_bkram_only.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2019, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of  the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
#ifndef	REGDEFS_H
#define	REGDEFS_H


//
// The @REGDEFS.H.INCLUDE tag
//
// @REGDEFS.H.INCLUDE for masters
// @REGDEFS.H.INCLUDE for peripherals
// And finally any master REGDEFS.H.INCLUDE tags
// End of definitions from REGDEFS.H.INCLUDE


//
// Register address definitions, from @REGS.#d
//
// CONSOLE registers
#define	R_CONSOLE_FIFO  	0x00004004	// 00004000, wbregs names: UFIFO
#define	R_CONSOLE_UARTRX	0x00004008	// 00004000, wbregs names: RX
#define	R_CONSOLE_UARTTX	0x0000400c	// 00004000, wbregs names: TX
// RTC clock registers
#define	R_CLOCK         	0x00008000	// 00008000, wbregs names: CLOCK
#define	R_TIMER         	0x00008004	// 00008000, wbregs names: TIMER
#define	R_STOPWATCH     	0x00008008	// 00008000, wbregs names: STOPWATCH
#define	R_CKALARM       	0x0000800c	// 00008000, wbregs names: ALARM, CKALARM
#define	R_CKSPEED       	0x00008010	// 00008000, wbregs names: CKSPEED
#define	R_BUILDTIME     	0x0000c000	// 0000c000, wbregs names: BUILDTIME
#define	R_BUILDTIME     	0x0000c000	// 0000c000, wbregs names: BUILDTIME
#define	R_BUSERR        	0x0000c004	// 0000c004, wbregs names: BUSERR
#define	R_BUSERR        	0x0000c004	// 0000c004, wbregs names: BUSERR
#define	R_PIC           	0x0000c008	// 0000c008, wbregs names: PIC
#define	R_PIC           	0x0000c008	// 0000c008, wbregs names: PIC
#define	R_PWRCOUNT      	0x0000c00c	// 0000c00c, wbregs names: PWRCOUNT
#define	R_PWRCOUNT      	0x0000c00c	// 0000c00c, wbregs names: PWRCOUNT
#define	R_SPIO          	0x0000c010	// 0000c010, wbregs names: SPIO
#define	R_SPIO          	0x0000c010	// 0000c010, wbregs names: SPIO
#define	R_VERSION       	0x0000c014	// 0000c014, wbregs names: VERSION
#define	R_VERSION       	0x0000c014	// 0000c014, wbregs names: VERSION
#define	R_BKRAM         	0x00010000	// 00010000, wbregs names: RAM


//
// The @REGDEFS.H.DEFNS tag
//
// @REGDEFS.H.DEFNS for masters
#define	R_ZIPCTRL	0x00020000
#define	R_ZIPDATA	0x00020004
// #define	RESET_ADDRESS	@$[0x%08x](RESET_ADDRESS)
#define	BAUDRATE	1000000
#define	CLKFREQHZ	50000000
// @REGDEFS.H.DEFNS for peripherals
#define	BKRAMBASE	0x00010000
#define	BKRAMLEN	0x00010000
// @REGDEFS.H.DEFNS at the top level
// End of definitions from REGDEFS.H.DEFNS
//
// The @REGDEFS.H.INSERT tag
//
// @REGDEFS.H.INSERT for masters

#define	CPU_GO		0x0000
#define	CPU_RESET	0x0040
#define	CPU_INT		0x0080
#define	CPU_STEP	0x0100
#define	CPU_STALL	0x0200
#define	CPU_HALT	0x0400
#define	CPU_CLRCACHE	0x0800
#define	CPU_sR0		0x0000
#define	CPU_sSP		0x000d
#define	CPU_sCC		0x000e
#define	CPU_sPC		0x000f
#define	CPU_uR0		0x0010
#define	CPU_uSP		0x001d
#define	CPU_uCC		0x001e
#define	CPU_uPC		0x001f

#ifdef	FLASH_ACCESS
#define	RESET_ADDRESS	0x00410000
#else
#define	RESET_ADDRESS	0x00010000
#endif


// @REGDEFS.H.INSERT for peripherals
// @REGDEFS.H.INSERT from the top level
typedef	struct {
	unsigned	m_addr;
	const char	*m_name;
} REGNAME;

extern	const	REGNAME	*bregs;
extern	const	int	NREGS;
// #define	NREGS	(sizeof(bregs)/sizeof(bregs[0]))

extern	unsigned	addrdecode(const char *v);
extern	const	char *addrname(const unsigned v);
// End of definitions from REGDEFS.H.INSERT


#endif	// REGDEFS_H
